{
    "editor.fontFamily": "JetBrainsMono-Regular",
    "editor.fontLigatures": true,
    "editor.detectIndentation": true,
    "editor.lightbulb.enabled": false,
    "editor.fontSize": 18,
    "editor.quickSuggestionsDelay": 30,
    "workbench.editor.tabSizing": "shrink",
    "html.format.enable": true,
    "html.format.preserveNewLines": true,
    "files.trimTrailingWhitespace": true,
    "editor.tabSize": 2,
    "editor.cursorWidth": 3,
    "editor.wordWrap": "on",
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.fontWeight": "400",
    "editor.cursorBlinking": "solid",
    "editor.minimap.enabled": false,
    "workbench.sideBar.location": "left",
    "editor.minimap.showSlider": "always",
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "[javascript]": {
      "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emmet.includeLanguages": {
      "javascript": "javascriptreact"
    },
    "editor.renderWhitespace": "boundary",
    "editor.cursorSmoothCaretAnimation": true,
    "editor.smoothScrolling": true,
    "editor.snippetSuggestions": "top",
    "editor.autoIndent": "keep",
    "files.insertFinalNewline": true,
    "editor.matchBrackets": "always",
    "window.openFilesInNewWindow": "off",
    "workbench.editor.enablePreview": true,
    "editor.scrollBeyondLastLine": true,
    "window.zoomLevel": 1,
    "editor.parameterHints.enabled": false,
    "terminal.integrated.fontSize": 16,
    "terminal.integrated.fontFamily": "JetBrainsMono-Regular",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "javascript.updateImportsOnFileMove.enabled": "always",
    "cSpell.language": "en-GB",
    "cSpell.userWords": [
      "Asam",
      "Cory",
      "DTOs",
      "Ethy",
      "Flickity",
      "GROQ",
      "Hacktoberfest",
      "Headspace",
      "Kubernetes",
      "Laravel",
      "Linkedin",
      "Linky",
      "Podcast",
      "Setup",
      "Trello",
      "Udemy",
      "arse",
      "blogging",
      "blogs",
      "deets",
      "factor",
      "firestore",
      "gonna",
      "importer",
      "mentee",
      "mentees",
      "placeholder",
      "podcasts",
      "podcats",
      "prepping",
      "renderable",
      "repos",
      "retirees",
      "rockstar",
      "shans",
      "todos",
      "wanna",
      "wellbeing",
      "wordpress"
    ],
    "workbench.colorTheme": "Dracula",
    "editor.formatOnSave": true
  }
  
