{
  "editor.fontFamily": "JetBrains Mono",
  "editor.fontLigatures": true,
  "editor.detectIndentation": true,
  "editor.lightbulb.enabled": false,
  "editor.fontSize": 14,
  "editor.lineHeight": 25,
  "editor.letterSpacing": 0.5,
  "files.trimTrailingWhitespace": true,
  "editor.cursorStyle": "line",
  "editor.cursorWidth": 2,
  "editor.quickSuggestionsDelay": 30,
  "workbench.editor.tabSizing": "shrink",
  "html.format.enable": true,
  "html.format.preserveNewLines": true,
  "editor.tabSize": 4,
  "editor.wordWrap": "on",
  "editor.multiCursorModifier": "ctrlCmd",
  "editor.fontWeight": "400",
  "editor.cursorBlinking": "blink",
  "editor.minimap.enabled": false,
  "workbench.sideBar.location": "left",
  "editor.minimap.showSlider": "always",
  "breadcrumbs.enabled": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "editor.cursorSmoothCaretAnimation": true,
  "editor.smoothScrolling": true,
  "editor.snippetSuggestions": "top",
  "editor.autoIndent": "keep",
  "files.insertFinalNewline": true,
  "editor.matchBrackets": "always",
  "window.openFilesInNewWindow": "off",
  "workbench.editor.enablePreview": true,
  "editor.scrollBeyondLastLine": true,
  "window.zoomLevel": 1,
  "editor.parameterHints.enabled": false,
  "terminal.integrated.fontSize": 14,
  "terminal.integrated.fontFamily": "MesloLGS NF",
  "editor.suggestSelection": "first",
  "typescript.updateImportsOnFileMove.enabled": "always",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "editor.renderWhitespace": "all",
  "cSpell.language": "en-GB",
  "editor.formatOnSave": true,
  "workbench.iconTheme": "city-lights-icons-vsc-light",
  "editor.renameOnType": true,
  "workbench.colorTheme": "Night Owl"
}
